### ISSUE TITLE
User tests don't match existing erb text

### ISSUE THREAD

**Issue by bacitracin** [learn-co-curriculum/sinatra-user-auth#10]
The existing text in the sign up and log in erb files should probably be updated to be capitalized so that it matches the Capybara tests. 'sign up' to 'Sign Up', 'log in' to 'Log In', etc.

**Comment by vicfriedman** [comment]
hey @bacitracin,

Can you provide more info about where you noticed o those links aren't capitalized? The forms are all empty for students to fill in.
