### ISSUE TITLE
Code along may be out of line with what works

### ISSUE THREAD

**Issue by aturkewi** [learn-co-curriculum/sinatra-user-auth#18]
I've seen a couple of suggestions that the code along may not be in line with what works for this lab.

https://github.com/learn-co-students/sinatra-user-auth-v-000/issues/66
https://learn.co/handraise_questions/28303

@lukeghenco not sure if you have time for this, but just tagging you because it's Sinatra.
cc @AnnJohn @PeterBell

**Comment by Lukeghenco** [comment]
Thanks @aturkewi I will add it to my list.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#25.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
