### ISSUE TITLE
@avidor Student unable to run `Rake db:migrate` as per lab instructions

### ISSUE THREAD

**Issue by mdjurdj1** [learn-co-curriculum/sinatra-user-auth#21]
With a fresh clone of the lab, student gets the following error when attempting to run migrate: 

**LoadError: cannot load such file -- active_record/railties/databases.rake**

I attempted to manually create the database, but student still ran into issues using Rake commands. Student was able to work on other labs which used Rake to build DBs/create migrations, so I suspect this lab may have some faulty instructions/dependencies (noted in the previously raised issue for this lab).

**Comment by DakotaLMartinez** [comment]
Ended up running bundle update and adding 
`require 'sinatra/activerecord'`
before
`require 'sinatra/activerecord/rake'`

rake -T seems to work fine now

**Comment by dapawn** [comment]
I just got this error. Added the following two lines to the Rakefile,
```
require 'sinatra'
require 'active_record'
```
before
```
require 'sinatra/activerecord/rake'
```

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#25.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
