### ISSUE TITLE
Broken lab

### ISSUE THREAD

**Issue by DoriansGrave** [learn-co-curriculum/sinatra-user-auth#22]
Something is wrong with either the tests or the code provided. Unable to get past a failed test because the element "email" could not be found (see screenshot). This was part of the supposedly working base code that was provided. Attempted multiple times to correct, replaced every page of my code with the solution (except for the application_controller.rb file, which was inexplicably not 'solved'), and still could not get past that error.
<img width="610" alt="screen shot 2017-07-03 at 6 07 25 pm" src="https://user-images.githubusercontent.com/26909418/27810016-ea6a243c-601a-11e7-855c-a9e6c3e8cbbe.png">

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#25.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
