### ISSUE TITLE
Solution branch does not pass tests

### ISSUE THREAD

**Issue by kwebster2** [learn-co-curriculum/sinatra-user-auth#24]
@cernanb 
The solution branch is not complete. There is a lot of logic missing from the controller.

**Comment by curiositypaths** [comment]
Thanks for reporting this issue. We're now aware of it and are tracking it in
#25.  We will add this to our internal work queue and notify you when it is resolved.

We're closing this issue but invite you to follow progress at that URL.

-- Flatiron Curriculum Team
