### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by curiositypaths** [learn-co-curriculum/sinatra-user-auth#25]
PROBLEM: Update instructions. , See issues #22, #21, #18
NOTIFY: @DoriansGrave, @mdjurdj1, @aturkewi 

PROBLEM: Update solution. See issues #24
NOTIFY: @kwebster2

**Comment by DanielSeehausen** [comment]
Updates to solution and master should address all of these issues
Code along now matches solution and tests better
solution branch is working
gemfile updated to require correct stuff (unable to reproduce issue after updates)

**Comment by DanielSeehausen** [comment]
To everyone who helped: @DoriansGrave, @mdjurdj1, @aturkewi, @kwebster2

Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by Sillhouette** [comment]
In the code along it tells us on multiple occasions to use the session[:id] when in the answer it uses session[:user_id] which causes multiple tests to fail. On another note, the tests don't actually test for whether the session was cleared on logout, and the answer logout route doesn't clear the session either. This defeats the purpose of including it in the lab.
