### ISSUE TITLE
NoMethodError in config/spec files

### ISSUE THREAD

**Issue by kfecho30** [learn-co-curriculum/sinatra-user-auth#27]
I was getting the following error when running the rspec test suite:
`NoMethodError: undefined method `needs_migration?' for ActiveRecord::Migrator:Class`

I was able to find this chunk of code in `config.ru` and `spec_helper.rb`:
```
if defined?(ActiveRecord::Migrator) && ActiveRecord::Migrator.needs_migration?
  raise 'Migrations are pending run `rake db:migrate SINATRA_ENV=test` to resolve the issue.'
end
```

When I comment this chunk out, the labs run fine, as does all database functionality.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
