### ISSUE TITLE
Having Trouble running learn here

### ISSUE THREAD

**Issue by shlokjoshi** [learn-co-curriculum/sinatra-user-auth#28]
NoMethodError: undefined method `needs_migration?' for ActiveRecord::Migrator:Class
  /home/shlokjoshi/sinatra-user-auth-cb-gh-000/spec/spec_helper.rb:8:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `require'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `block in requires='
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `each'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration.rb:1455:in `requires='
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `each'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/configuration_options.rb:21:in `configure'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:99:in `setup'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:86:in `run'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:71:in `run'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/lib/rspec/core/runner.rb:45:in `invoke'
  /usr/local/rvm/gems/ruby-2.3.1/gems/rspec-core-3.7.1/exe/rspec:4:in `<top (required)>'
  /usr/local/rvm/gems/ruby-2.3.1/bin/rspec:23:in `load'
  /usr/local/rvm/gems/ruby-2.3.1/bin/rspec:23:in `<top (required)>'

**Comment by oconnojb** [comment]
I was helped with this issue earlier. To fix this error, I was told to change the Gemfile. 
Instead of `gem 'activerecord'` it should be `gem 'activerecord', '4.2', :require => 'active_record'`

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
