### ISSUE TITLE
Codealong test left unpassed?

### ISSUE THREAD

**Issue by oconnojb** [learn-co-curriculum/sinatra-user-auth#30]
Hello,
When completing this codealong lab, it left one of the tests unsolved:

```
    it 'fails to log in with an incorrect password' do
      expect(current_path).to eq('/sessions/login')
      fill_in("email", :with => valid_user.email)
      fill_in("password", :with => "wrong")
      click_button('Log In')
      expect(current_path).to eq('/sessions/login')
    end
```

specifically, _(# ./spec/features/user_feature_spec.rb:46)_ causes this failure:

```
  expected: "/sessions/login"
  got: "/sessions"
```

I was able to get the test to pass by checking with an `if` statement to make sure the computer had been able to find the correct User:

```
  post '/sessions' do
    @user = User.find_by(email: params["email"], password: params["password"])
    if @user == nil
      redirect '/sessions/login'
    else
      session[:id] = @user.id
      redirect '/users/home'
    end
  end
```

If your intention was to get students to figure it out on their own, it worked!  
:)

**Comment by drakeltheryuujin** [comment]
Thanks for reporting this issue. We're aware of it and are tracking it in #36.
We're closing this issue but invite you to follow #36.
