### ISSUE TITLE
Apply Migrations To The Correct Database

### ISSUE THREAD

**Issue by ecssiah** [learn-co-curriculum/sinatra-user-auth#31]
There are two databases that come with this lab. It should probably be mentioned in the README that it is necessary to run `rake db:migrate SINATRA_ENV=test` in order to build the schema in the right database. If `rake db:migrate` is run like the README suggests, then it populates "user_authdevelopment.sqlite" database, but this one is not the one used by the specs.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
