### ISSUE TITLE
Error with Rake and rspec

### ISSUE THREAD

**Issue by coryjbergquist** [learn-co-curriculum/sinatra-user-auth#35]
Rake was not running correctly, so changed rakefile to:

require_relative './config/environment'
require 'sinatra/activerecord/rake'

rspec giving error of: 

bundler: failed to load command: rspec (/usr/local/rvm/gems/ruby-2.3.1/bin/rspec)
NoMethodError: undefined method `needs_migration?' for ActiveRecord::Migrator:Class

**Comment by cassaram09** [comment]
Was getting a similar error of not being able to find `sinatra/activerecord/rake` when attempting to run `rake db:migrate`. Moving the `require_relative './config/environment'` before `require 'sinatra/activerecord/rake'` seemed to fix it.

**Comment by d-d-d-dalia** [comment]
also need the right Active Record version in gemfile: 

gem 'activerecord', '4.2', :require => 'active_record'

**Comment by coryjbergquist** [comment]
I've also seen that running `bundle exec rake db:migrate` will work as well

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
