### ISSUE TITLE
Known Issues

### ISSUE THREAD

**Issue by drakeltheryuujin** [learn-co-curriculum/sinatra-user-auth#36]
PROBLEM: Issues with codealong as well as the solution
#34 
NOTIFY: @Sillhouette 

PROBLEM: !codalong
#32 
NOTIFY: @netzay

PROBLEM: Codealong test left unpassed?
#30 
NOTIFY: @oconnojb

**Comment by d-d-d-dalia** [comment]
Had a situation with #30 today. The fix noted in the issue fixed it.
