### ISSUE TITLE
Solution Error Fix

### ISSUE THREAD

**Issue by meg-gutshall** [learn-co-curriculum/sinatra-user-auth#40]
Found errors in two controller action blocks. Please see my comments in [PR #1149](https://github.com/learn-co-students/sinatra-user-auth-v-000/pull/1149).

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.
We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.
If you do not believe that this issue has been addressed, please re-open this issue.

**Comment by meg-gutshall** [comment]
Thank you Kellye,

I'm just a little confused. I thought that if I opened a pull request with
the needed changes, it would be merged into the main repo's solution
branch. Is that not how the Git flow is supposed to work? I want to make
sure I have this right for when I want to contribute to other repos.

Thanks,
Meg
