### ISSUE TITLE
So many issues with this code along

### ISSUE THREAD

**Issue by JoeQuattrone** [learn-co-curriculum/sinatra-user-auth#42]
Basically ran into issues with the test every step of the way. Im not even going to list them because it would take too long. It needs a complete fix.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
