### ISSUE TITLE
README Incorrect - session[:id] to session[:user_id]

### ISSUE THREAD

**Issue by brennanmrose** [learn-co-curriculum/sinatra-user-auth#43]
Hi there, 

Looks like the README needs to be updated in this lab. There are several times in the controller where 'session[:user_id]' is listed, but the README says to enter session[:id] in two different spots. I did so, following the README and it took a while to figure out that the README was just wrong and the code that came with the lab was actually correct. Seems like a simple fix that would save a bunch of folks a lot of time? 

Thank you!
Rose

**Comment by Sdcrouse** [comment]
I think this has been fixed.
