### ISSUE TITLE
db/migrate: Update File Name Required to Pass 1st Test

### ISSUE THREAD

**Issue by ccklight** [learn-co-curriculum/sinatra-user-auth#46]
Hi, 

To pass this first Step 1: Migration requires a _01 in front of the file name. Example:  db/migrate/01_create_users_table.rb
 
I would not have intuited or thought of that. Over 1 hour to figure out and then with AAQ. 

Please make it clearer in the lesson. 

*******
Step 1: Migration
Write a migration that creates a Users table with columns for name, email, and password. Run rake db:migrate SINATRA_ENV=test and then run your test suite.

You'll see that you're passing a number of tests, including these:

User
  is invalid without a name
  is invalid without a email
  is invalid without an password

**Comment by Sdcrouse** [comment]
This part of the lesson was definitely tricky. What I did was `rake db:create_migration NAME=create_users`. That created a timestamped migration file for me automatically, and then all I needed to do was fill in the columns (`t.string :name, t.string :email`, etc).

I hope that helps! Peace.
